# Generated by Django 3.1.3 on 2020-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuedetails',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='venuedetails',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
